# Site settings.

# Without a clear rule enforced, both title and name are used.
title: GNU ARM Eclipse
name: GNU ARM Eclipse
description: A family of Eclipse CDT extensions and tools for GNU ARM development
email: il@livius.net

destination: _site
exclude:
  - README.md
  - jekyll-build.command
  - jekyll-serve.command
  - atom.command
  - localhost-4000.webloc

# The subpath of your site, e.g. /blog (note the leading slash and the
# absence of a trailing slash).
baseurl: ""

# Used in sitemap.xml
url: "http://gnuarmeclipse.github.io" # the base hostname & protocol for your site

# This timezone is used to display post dates and last modified messages.
timezone: UTC

encoding: utf-8

# Default permalink used for posts
permalink: /blog/:year/:month/:day/:title/

# Currently disabled, since it generates incomplete content.
# Use manually written RSS feed.xml.
#   - jekyll-feed
# {% feed_meta %} in head.html

gems:
  - jekyll-last-modified-at
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

# Build settings
markdown: kramdown
# markdown: redcarpet

kramdown:
  input: GFM

redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
    - highlight
    - with_toc_data
    - safe_links_only

# Warning: paginator retired in Jekyll 3!
# Make this larger, probably 5 is a good choice.
paginate: 10
paginate_path: "/blog/page:num/"

# The number of links added to the 'Latest news' box.
latest-news-pages: 5

# Custom defs
github-username:  ilg-ul

github-project-name: gnuarmeclipse
github-project-url: http://github.com/gnuarmeclipse
sourceforge-project-url: http://sourceforge.net/projects/gnuarmeclipse

facebook-page: https://facebook.com/gnuarmeclipse/

google-analytics-id: UA-16767008-16
google-site-verification: NT_y3tqI_8mrd8gYA_FDWHT2-tkJExOC6KBkSnyZx6c

# jekyll-toc-generator
tocTopTag: h2
minItemsToShowToc: 3
useExistingAnchors: true

css-date: 201510051605

# Content copyright. Update it to your needs.
copyright-message: "Â© 2015 Liviu Ionescu"
